name: CI/CD Non-prod

on:
  push:
    paths:
      - 'non-prod/**'
      - '.github/workflows/ci-cd-nonprod.yml'
    branches:
      - stage
  workflow_dispatch:

env:
  BUCKET_NAME: tf-state-nonprod1 # Replace with your bucket name.
  SA_ACC: project-service-account@nonprod1-svc-6u24.iam.gserviceaccount.com  # Replace with your service account.
  CLUSTER_NAME: nonprod1-clusterk8s # Replace with you cluster name (you_cluster_name-clusterk8s).
  REGION: us-central1 # Replace with you region.

jobs:
  Infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./non-prod/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Decode credentials
        run: echo "${{ secrets.GCP_CREDENTIALS_NONPROD1 }}" | base64 -d > credentials_file.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud config set account ${SA_ACC}
          gcloud auth activate-service-account --key-file=credentials_file.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID_NONPROD1 }}

      - name: Create bucket if dosn't exists
        env:
          SCRIPT_DIR: ${{ github.workspace }}/non-prod/scripts
        run: bash $SCRIPT_DIR/create-bucket.sh
          
      - name: terraform init
        run: terraform init -backend-config="bucket=${BUCKET_NAME}"

      - name: terraform plan
        run: terraform plan -lock=false -var="project_id=${{ secrets.GCP_PROJECT_ID_NONPROD1 }}"
        
      - name: terraform apply 
        if: "!contains(github.event.head_commit.message, 'destroy')"
        run: terraform apply -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID_NONPROD1 }}" 

      - name: Terraform Destroy
        if: contains(github.event.head_commit.message, 'destroy')
        run: terraform destroy -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID_NONPROD1 }}"   
  
  Deployment:
    needs:
      - Infrastructure 
    if: "contains(github.event.head_commit.message, 'init') "
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./non-prod   
          
    steps:
      - name: Clon Rep
        uses: actions/checkout@v3
      
      - name: Decode credentials
        run: echo "${{ secrets.GCP_CREDENTIALS_NONPROD1 }}" | base64 -d > credentials_file.json
      
      - name: Authenticate with Google Cloud
        run: |
          gcloud config set account ${SA_ACC}
          gcloud auth activate-service-account --key-file=credentials_file.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID_NONPROD1 }}
      
      - name: Auth Plugin for cluster
        uses: simenandre/setup-gke-gcloud-auth-plugin@v1
      
      - name: Get kubeconfig 
        run: gcloud container clusters get-credentials $CLUSTER_NAME --region=$REGION --project=${{ secrets.GCP_PROJECT_ID_NONPROD1 }}

      - name: Deploy Chatwoot
        env:
          SCRIPT_DIR: ${{ github.workspace }}/non-prod/scripts
        run: bash $SCRIPT_DIR/init-chatwoot.sh

      - name: Wait for 5 minutes
        run: sleep 300s

      - name: Deploy Novu
        env:
          SCRIPT_DIR: ${{ github.workspace }}/non-prod/scripts
        run: bash $SCRIPT_DIR/init-novu.sh
